# Generated by Django 6.0.3 on 2026-06-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contato',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
